name: PR / Canary Libs

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - libs/**

jobs:
  canary-libs:
    uses: beyonk-group/workflows/.github/workflows/canary-libs.yml@main
    secrets: inherit
    with:
      use_playwright: true